name: CI for this vulnerable application
on: [push]

jobs:
  
  sast_scan:
    
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Install bandit
        run: pip install bandit

      - name: Run bandit scan  // checking for bandit scan
        run: bandit -ll -ii -r . -f json -o bandit-report.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-findings
          path: bandit-report.json


  image_scan:
    name: Build docker image and run image scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Build image (load locally)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockefile
          load: true
          tags: myapp:local
      
      - name: Install docker scout cli
        run: |
          mkdir -p ~/.docker/cli-plugins
          curl -sSfL https://github.com/docker/scout-cli/releases/latest/download/docker-scout-linux-amd64 \
            -o ~/.docker/cli-plugins/docker-scout
          chmod +x ~/.docker/cli-plugins/docker-scout
          docker scout version
      
      - name: Docker scout quickview
        run: docker scout quickview myapp:local
        
      - name: Docker scout CVEs (table + SARIF)
        run: |
          docker scout cves --format table myapp:local > scout-cves.txt
          docker scout cves --format sarif -o scout.sarif myapp:local 

      - name : Upload Scout artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-scout-reports
          path: |
            scout-cves.txt
            scout.sarif

      - name: Upload sarif to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: scout.sarif

